import "server-only"

import { appConfig } from "@/lib/config/config.server"
import {
  appendPromptHistory,
  isTaskStarted,
  readPromptHistory,
  readTaskData,
} from "@/lib/onboarding/repository"
import {
  cleanupForbiddenWorkbenchFiles,
  filterWorkbenchPayloadByAllowlist,
  getLevelEditableWorkbenchFileMap,
  getLevelEditableWorkbenchFiles,
} from "@/lib/task/task-workbench.server"
import {
  clearTaskCheckResult,
  failCurrentTaskLevelCheck,
  getAllLevelOverviews,
  getLevelById,
  getLevelForTaskItem,
  getLevelOverview,
  getLevelsCatalog,
  getTaskCheckResult,
  getTaskDoneTransition,
  getTaskLabContext,
  getTaskListItemById,
  getTaskListItemsWithProgress,
  getTaskPendingTransition,
  markCurrentTaskLevelInitialized,
  markCurrentTaskLevelCheckTechnicalError,
  markTaskLevelInProgress,
  passCurrentTaskLevelCheck,
  resetTask,
  registerPromptForCurrentLevel,
  saveTaskCheckResult,
} from "@/lib/task/task-levels.server"

export {
  appConfig,
  appendPromptHistory,
  clearTaskCheckResult,
  cleanupForbiddenWorkbenchFiles,
  failCurrentTaskLevelCheck,
  filterWorkbenchPayloadByAllowlist,
  getAllLevelOverviews,
  getLevelById,
  getLevelForTaskItem,
  getTaskCheckResult,
  getTaskDoneTransition,
  getLevelOverview,
  getLevelsCatalog,
  getLevelEditableWorkbenchFileMap,
  getLevelEditableWorkbenchFiles,
  getTaskLabContext,
  getTaskListItemById,
  getTaskListItemsWithProgress as getTaskListItems,
  getTaskPendingTransition,
  isTaskStarted,
  markCurrentTaskLevelInitialized,
  markCurrentTaskLevelCheckTechnicalError,
  markTaskLevelInProgress,
  passCurrentTaskLevelCheck,
  readPromptHistory,
  readTaskData,
  resetTask,
  registerPromptForCurrentLevel,
  saveTaskCheckResult,
}
