import "server-only"

import { appConfig } from "./config.server"
import {
  appendPromptHistory,
  isTaskStarted,
  readPromptHistory,
  readTaskData,
} from "./repository"
import { publishTaskSnapshot, readPublishedSnapshot } from "./snapshot.server"
import {
  cleanupForbiddenWorkbenchFiles,
  filterWorkbenchPayloadByAllowlist,
  getLevelEditableWorkbenchFileMap,
  getLevelEditableWorkbenchFiles,
} from "./task-workbench.server"
import {
  clearTaskCheckResult,
  failCurrentTaskLevelCheck,
  getAllLevelOverviews,
  getLevelById,
  getLevelForTaskItem,
  getLevelOverview,
  getLevelsCatalog,
  getTaskCheckResult,
  getTaskDoneTransition,
  getTaskLabContext,
  getTaskListItemById,
  getTaskListItemsWithProgress,
  getTaskPendingTransition,
  markCurrentTaskLevelInitialized,
  markCurrentTaskLevelCheckTechnicalError,
  markTaskLevelInProgress,
  passCurrentTaskLevelCheck,
  resetTask,
  registerPromptForCurrentLevel,
  saveTaskCheckResult,
} from "./task-levels.server"

export {
  appConfig,
  appendPromptHistory,
  clearTaskCheckResult,
  cleanupForbiddenWorkbenchFiles,
  failCurrentTaskLevelCheck,
  filterWorkbenchPayloadByAllowlist,
  getAllLevelOverviews,
  getLevelById,
  getLevelForTaskItem,
  getTaskCheckResult,
  getTaskDoneTransition,
  getLevelOverview,
  getLevelsCatalog,
  getLevelEditableWorkbenchFileMap,
  getLevelEditableWorkbenchFiles,
  getTaskLabContext,
  getTaskListItemById,
  getTaskListItemsWithProgress as getTaskListItems,
  getTaskPendingTransition,
  isTaskStarted,
  markCurrentTaskLevelInitialized,
  markCurrentTaskLevelCheckTechnicalError,
  markTaskLevelInProgress,
  passCurrentTaskLevelCheck,
  publishTaskSnapshot,
  readPromptHistory,
  readPublishedSnapshot,
  readTaskData,
  resetTask,
  registerPromptForCurrentLevel,
  saveTaskCheckResult,
}
